Adding clusterroles feature. Fixes #51
kdash-rs/kdash pull request #236
Opened 2022-08-06 20:44 UTC by shinusuresh

2022-08-07 08:54 UTC, deepu105 requested changes

2022-08-07 08:54 UTC, deepu105 commented on src/ui/resource_tabs.rs
> +static CLUSTER_ROLES_TITLE: &str = "Cluster Roles";
Remove space 
```suggestion
static CLUSTER_ROLES_TITLE: &str = "ClusterRoles";
```

2022-08-07 08:54 UTC, deepu105 commented on src/ui/resource_tabs.rs
> +    },
Colums should add up to 100

2022-08-07 11:37 UTC, shinusuresh commented on src/ui/resource_tabs.rs
> +    },
Done

2022-08-07 11:37 UTC, shinusuresh commented on src/ui/resource_tabs.rs
> +static CLUSTER_ROLES_TITLE: &str = "Cluster Roles";
Done

2022-08-08 20:13 UTC, deepu105 approved these changes

2022-08-11 13:03 UTC, merged