Added support for CronJobs
kdash-rs/kdash pull request #69
Opened 2021-06-26 19:47 UTC by somayaj

2021-06-29 11:54 UTC, deepu105 requested changes
some comments, also will wait for the UI part to be added

2021-06-29 11:54 UTC, deepu105 commented on src/app/cronjobs.rs
> +  pub name: String,
need to align with what kubectl shows

2021-06-29 11:54 UTC, deepu105 commented on test_data/cronjobs.yaml
> +apiVersion: v1
should be generated form `kubectl get cronjobs -o yaml`

2021-07-05 10:00 UTC, deepu105 commented
@somayaj I fixed the parsing and tests. Can you add the section to the UI please

2021-07-05 13:13 UTC, somayaj commented
i didn;t get that actually. What files are those?

On Mon, Jul 5, 2021 at 5:01 AM Deepu K Sasidharan ***@***.***>
wrote:

> @somayaj <https://github.com/somayaj> I fixed the parsing and tests. Can
> you add the section to the UI please
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kdash-rs/kdash/pull/69#issuecomment-873980841>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIRAZGIZE4YGHDAS6A4TXSLTWF7GBANCNFSM47LUQAVA>
> .
>

2021-07-05 14:13 UTC, deepu105 commented
I mean to make cronjobs appear in the UI, you need to add the rendering code under ui/overview.rs. you can follow what is already there for jobs and replicate that

2021-07-05 15:50 UTC, somayaj commented
> I mean to make cronjobs appear in the UI, you need to add the rendering code under ui/overview.rs. you can follow what is already there for jobs and replicate that

My bad, I thought I had those in the initial commit. I've checked them in now.

2021-07-05 20:51 UTC, deepu105 requested changes

2021-07-05 20:51 UTC, deepu105 commented on src/ui/overview.rs
> +        Constraint::Percentage(25),
Total percentage needs to be 99 else we will have out of bound errors

2021-07-06 07:55 UTC, deepu105 approved these changes

2021-07-06 07:55 UTC, merged